const r = require('express').Router();
const c = require('../controllers/user.controller');
const { authenticate, requireRole } = require('../middleware/auth.middleware');
r.use(authenticate);
r.get('/',       requireRole('admin'), c.listar);
r.post('/',      requireRole('admin'), c.criar);
r.patch('/:id',  requireRole('admin'), c.atualizar);
r.delete('/:id',              requireRole('admin'), c.desativar);
r.post('/:id/reset-senha',   requireRole('admin'), c.resetSenha);
module.exports = r;
